# Generated by Django 5.2.13 on 2026-04-18 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_label', models.CharField(max_length=64)),
                ('subtitle', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('search_hint', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('price_label', models.CharField(max_length=64)),
                ('price_note', models.CharField(blank=True, max_length=64)),
                ('badge', models.CharField(blank=True, max_length=64, null=True)),
                ('footer_line', models.CharField(blank=True, max_length=100)),
                ('footer_icon', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('telegram', models.CharField(blank=True, max_length=64)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('main_image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='vendors.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Mehmon', max_length=100)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vendors.vendor')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'vendor'), name='uniq_user_vendor_favorite')],
            },
        ),
    ]
